version: "3.9"
services:
  web:
    depends_on:
      - db
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: gyanny-auth
    env_file:
      - web/.env
    ports:
      - "8000:8000"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && gunicorn --bind=0.0.0.0:8000 gyanny_k8s.wsgi:application"
  db:
    image: postgres:13.0-alpine
    container_name: db
    restart: always
    command: -p 5432
    env_file:
      - web/.env
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
